#!/bin/bash

# API_URL="https://pokeapi.co/api/v2/pokemon"
# POKEMAN="ditto"


OUTPUT_FILE="data.json"


ERROR_FILE="errors.txt"

# Make API request and handle errors
echo "Fetching Pokémon data for Ditto ..."
# RESPONSE=$(curl -s -w "%{http_code}" -o "$OUTPUT_FILE" "$API_URL/$POKEMAN")
RESPONSE=$(curl -s -w "%{http_code} - o "$OUTPUT_FILE" "https://pokeapi.co/api/v2/pokemon/ditto")


# Extract HTTP status code
HTTP_STATUS=${RESPONSE: -3}

if [ "$HTTP_STATUS" -eq 200 ]; then
    echo "Successfully fetched data. Saved to $OUTPUT_FILE."
else
    echo "Failed to fetch data. HTTP Status: $HTTP_STATUS" | tee -a "$ERROR_FILE"
fi